<?php

$title = 'My countrys';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('country', array('action'=>'add'));?>">Add new country</a>
</p>

<table class="table">
<tr>
    <th>Alpha3</th>
    <th>French name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($countrys as $country) : ?>
<tr>
    <td><?php echo $this->escapeHtml($country->alpha3);?></td>
    <td><?php echo $this->escapeHtml($country->nomFrFr);?></td>
    <td>
        <a href="<?php echo $this->url('country',
            array('action'=>'edit', 'id' => $country->id));?>">Edit</a>
        <a href="<?php echo $this->url('country',
            array('action'=>'delete', 'id' => $country->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>